name: dbtvault_snowflake_demo
profile: dbtvault_snowflake_demo
version: '5.0.0'
require-dbt-version: ['>=0.18.0', '<0.19.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '2002-01-05'
  src-cd: P10 #1, C11, E03
  
models:
    dbtvault_snowflake_demo:
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'
      pit:
        materialized: pit_incremental
        tags:
          - pit
        pit_customer:
          vars:
            source_model: HUB_CUSTOMER
            as_of_date_table: AS_OF_DATES
            src_pk: CUSTOMER_HK
            satellites: 
                SAT_CUSTOMER_P10_KNA1:
                    pk:
                        'PK': 'CUSTOMER_HK'
                    ldts:
                        'LDTS': 'LOAD_EFF_DT'
   