SELECT 
I_ITEM_ID AS ITEM_ID,
I_REC_END_DATE AS REC_END_DATE,
I_REC_START_DATE AS REC_START_DATE,
I_ITEM_DESC AS ITEM_DESC,
I_BRAND AS BRAND,
I_BRAND_ID AS BRAND_ID,
I_CATEGORY AS CATEGORY,
I_CATEGORY_ID AS CATEGORY_ID,
I_CLASS AS CLASS,
I_CLASS_ID AS CLASS_ID,
I_COLOR AS COLOR,
I_CONTAINER AS CONTAINER,
I_CURRENT_PRICE AS CURRENT_PRICE,
I_FORMULATION AS FORMULATION,
I_MANAGER_ID AS MANAGER_ID,
I_MANUFACT AS MANUFACT,
I_MANUFACT_ID AS MANUFACT_ID,
I_PRODUCT_NAME AS PRODUCT_NAME,
I_SIZE AS SIZE,
I_UNITS AS UNITS,
I_WHOLESALE_COST AS WHOLESALE_COST
from {{ source('tpch_sample', 'ITEM') }} i
where ITEM_ID IN (SELECT ITEM_ID FROM {{ ref('raw_store_sales') }} )
