version: 2

sources:
  - name: sapc11_tbl
    database: RAW
    schema: SAP{{ var('src-cd', C11) }} 
    tables:
      - name: A017
      - name: A601
      - name: A602
      - name: AUFK
      - name: BKPF
      - name: BSAK
      - name: BSEG
      - name: BSIK
      - name: CEPC
      - name: CEPCT
      - name: CSKS
      - name: CSKT
      - name: EBAN
      - name: EBANFORECAST
      - name: EBKN
      - name: EINA
      - name: EINE
      - name: EIPA
      - name: EKBE
      - name: EKES
      - name: EKET
      - name: EKETFORECAST
      - name: EKKN
      - name: EKKO
      - name: EKKOLTD
      - name: EKPO
      - name: EKPOELIKZ
      - name: EKPOLTD
      - name: EORD
      - name: EQUZ
      - name: KNA1
      - name: KNAS
      - name: KNB1
      - name: KNB5
      - name: KNBK
      - name: KNC1
      - name: KNKA
      - name: KNKK
      - name: KNMT
      - name: KNVA
      - name: KNVH
      - name: KNVI
      - name: KNVK
      - name: KNVL
      - name: KNVP
      - name: KNVV
      - name: KONP
      - name: LFA1
      - name: LFB1
      - name: LFBK
      - name: LFBW
      - name: LFM1
      - name: LIKP
      - name: LIPS
      - name: MAKT
      - name: MARA
      - name: MARC
      - name: MARD
      - name: MARM
      - name: MAST
      - name: MBEW
      - name: MBEWH
      - name: MKOL
      - name: MKPF
      - name: MLAN
      - name: MLGN
      - name: MLGT
      - name: MSEG
      - name: MSKA
      - name: MSKU
      - name: MSLB
      - name: MVKE
      - name: PLMZ
      - name: RSEG
      - name: S032
      - name: SKA1
      - name: SKAT
      - name: STAS
      - name: STKO
      - name: STPO
      - name: STZU
      - name: T001
      - name: T001K
      - name: T001L
      - name: T001W
      - name: T003T
      - name: T005U
      - name: T006
      - name: T006A
      - name: T023T
      - name: T024
      - name: T024E
      - name: T052
      - name: T052U
      - name: T077Y
      - name: T077Z
      - name: T134T
      - name: T161
      - name: T161T
      - name: TCURR
      - name: TCURX
      - name: TGSB
      - name: TGSBT
      - name: TPAUM
      - name: TVKOT
      - name: VAKPA
      - name: VBAK
      - name: VBAKUK
      - name: VBAP
      - name: VBBE
      - name: VBEP
      - name: VBFA
      - name: VBKD
      - name: VBPA
      - name: VBRK
      - name: VBRP
      - name: VBUK
      - name: VBUP
      - name: VBUV
      - name: VEDA
      - name: WYT3
  - name: sape03_tbl
    database: RAW
    schema: SAP{{ var('src-cd', P10) }} 
    tables:
      - name: A017
      - name: A601
      - name: A602
      - name: AUFK
      - name: BKPF
      - name: BSAK
      - name: BSEG
      - name: BSIK
      - name: CEPC
      - name: CEPCT
      - name: CSKS
      - name: CSKT
      - name: EBAN
      - name: EBANFORECAST
      - name: EBKN
      - name: EINA
      - name: EINE
      - name: EIPA
      - name: EKBE
      - name: EKES
      - name: EKET
      - name: EKETFORECAST
      - name: EKKN
      - name: EKKO
      - name: EKKOLTD
      - name: EKPO
      - name: EKPOELIKZ
      - name: EKPOLTD
      - name: EORD
      - name: EQUZ
      - name: KNA1
      - name: KNAS
      - name: KNB1
      - name: KNB5
      - name: KNBK
      - name: KNC1
      - name: KNKA
      - name: KNKK
      - name: KNMT
      - name: KNVA
      - name: KNVH
      - name: KNVI
      - name: KNVK
      - name: KNVL
      - name: KNVP
      - name: KNVV
      - name: KONP
      - name: LFA1
      - name: LFB1
      - name: LFBK
      - name: LFBW
      - name: LFM1
      - name: LIKP
      - name: LIPS
      - name: MAKT
      - name: MARA
      - name: MARC
      - name: MARD
      - name: MARM
      - name: MAST
      - name: MBEW
      - name: MBEWH
      - name: MKOL
      - name: MKPF
      - name: MLAN
      - name: MLGN
      - name: MLGT
      - name: MSEG
      - name: MSKA
      - name: MSKU
      - name: MSLB
      - name: MVKE
      - name: PLMZ
      - name: RSEG
      - name: S032
      - name: SKA1
      - name: SKAT
      - name: STAS
      - name: STKO
      - name: STPO
      - name: STZU
      - name: T001
      - name: T001K
      - name: T001L
      - name: T001W
      - name: T003T
      - name: T005U
      - name: T006
      - name: T006A
      - name: T023T
      - name: T024
      - name: T024E
      - name: T052
      - name: T052U
      - name: T077Y
      - name: T077Z
      - name: T134T
      - name: T161
      - name: T161T
      - name: TCURR
      - name: TCURX
      - name: TGSB
      - name: TGSBT
      - name: TPAUM
      - name: TVKOT
      - name: VAKPA
      - name: VBAK
      - name: VBAKUK
      - name: VBAP
      - name: VBBE
      - name: VBEP
      - name: VBFA
      - name: VBKD
      - name: VBPA
      - name: VBRK
      - name: VBRP
      - name: VBUK
      - name: VBUP
      - name: VBUV
      - name: VEDA
      - name: WYT3
  - name: sapp10_tbl
    database: RAW
    schema: SAP{{ var('src-cd', P10) }} 
    tables:
      - name: A017
      - name: A601
      - name: A602
      - name: AUFK
      - name: BKPF
      - name: BSAK
      - name: BSEG
      - name: BSIK
      - name: CEPC
      - name: CEPCT
      - name: CSKS
      - name: CSKT
      - name: EBAN
      - name: EBANFORECAST
      - name: EBKN
      - name: EINA
      - name: EINE
      - name: EIPA
      - name: EKBE
      - name: EKES
      - name: EKET
      - name: EKETFORECAST
      - name: EKKN
      - name: EKKO
      - name: EKKOLTD
      - name: EKPO
      - name: EKPOELIKZ
      - name: EKPOLTD
      - name: EORD
      - name: EQUZ
      - name: KNA1
      - name: KNAS
      - name: KNB1
      - name: KNB5
      - name: KNBK
      - name: KNC1
      - name: KNKA
      - name: KNKK
      - name: KNMT
      - name: KNVA
      - name: KNVH
      - name: KNVI
      - name: KNVK
      - name: KNVL
      - name: KNVP
      - name: KNVV
      - name: KONP
      - name: LFA1
      - name: LFB1
      - name: LFBK
      - name: LFBW
      - name: LFM1
      - name: LIKP
      - name: LIPS
      - name: MAKT
      - name: MARA
      - name: MARC
      - name: MARD
      - name: MARM
      - name: MAST
      - name: MBEW
      - name: MBEWH
      - name: MKOL
      - name: MKPF
      - name: MLAN
      - name: MLGN
      - name: MLGT
      - name: MSEG
      - name: MSKA
      - name: MSKU
      - name: MSLB
      - name: MVKE
      - name: PLMZ
      - name: RSEG
      - name: S032
      - name: SKA1
      - name: SKAT
      - name: STAS
      - name: STKO
      - name: STPO
      - name: STZU
      - name: T001
      - name: T001K
      - name: T001L
      - name: T001W
      - name: T003T
      - name: T005U
      - name: T006
      - name: T006A
      - name: T023T
      - name: T024
      - name: T024E
      - name: T052
      - name: T052U
      - name: T077Y
      - name: T077Z
      - name: T134T
      - name: T161
      - name: T161T
      - name: TCURR
      - name: TCURX
      - name: TGSB
      - name: TGSBT
      - name: TPAUM
      - name: TVKOT
      - name: VAKPA
      - name: VBAK
      - name: VBAKUK
      - name: VBAP
      - name: VBBE
      - name: VBEP
      - name: VBFA
      - name: VBKD
      - name: VBPA
      - name: VBRK
      - name: VBRP
      - name: VBUK
      - name: VBUP
      - name: VBUV
      - name: VEDA
      - name: WYT3