version: 2

sources:
  - name: tpch_sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF{{ var('tpch_size', 10) }}TCL
    tables:
      - name: CUSTOMER
      - name: CUSTOMER_ADDRESS
      - name: STORE_SALES
      - name: WEB_SALES
      - name: INVENTORY
      - name: ITEM
      - name: DATE_DIM
      - name: TIME_DIM
      - name: WAREHOUSE
      - name: STORE